apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_result
      resources:
        limits:
          cpu: 100mi
          memory: 200m
      ports:
        - containerPort: 80